.PHONY: clean All

All:
	@echo "----------Building project:[ 84_RangeBasedForLoop - Debug ]----------"
	@cd "84_RangeBasedForLoop" && "$(MAKE)" -f  "84_RangeBasedForLoop.mk"
clean:
	@echo "----------Cleaning project:[ 84_RangeBasedForLoop - Debug ]----------"
	@cd "84_RangeBasedForLoop" && "$(MAKE)" -f  "84_RangeBasedForLoop.mk" clean
