.PHONY: clean All

All:
	@echo "----------Building project:[ 90_ProgrammingChallange - Debug ]----------"
	@cd "90_ProgrammingChallange" && "$(MAKE)" -f  "90_ProgrammingChallange.mk"
clean:
	@echo "----------Cleaning project:[ 90_ProgrammingChallange - Debug ]----------"
	@cd "90_ProgrammingChallange" && "$(MAKE)" -f  "90_ProgrammingChallange.mk" clean
