.PHONY: clean All

All:
	@echo "----------Building project:[ 107_OverloadingFunctions - Debug ]----------"
	@cd "107_OverloadingFunctions" && "$(MAKE)" -f  "107_OverloadingFunctions.mk"
clean:
	@echo "----------Cleaning project:[ 107_OverloadingFunctions - Debug ]----------"
	@cd "107_OverloadingFunctions" && "$(MAKE)" -f  "107_OverloadingFunctions.mk" clean
